In [2]:
import pandas as pd
df=pd.read_csv("data_cleaning_dataset.csv")
print(df.head(200))

     Row Labels  Sum of Monthly_Income  Sum of Purchase_Amount  Sum of Age
0        Female           1.605032e+07            2.301078e+06        9442
1     Bangalore           4.018235e+06            5.515569e+05        2703
2       Chennai           3.848587e+06            6.154198e+05        1560
3         Delhi           4.118840e+06            5.275939e+05        2406
4        Mumbai           4.064661e+06            6.065069e+05        2773
5          Male           1.654278e+07            2.484800e+06        9241
6     Bangalore           4.860467e+06            6.755198e+05        2470
7       Chennai           3.301398e+06            5.295149e+05        1868
8         Delhi           4.475052e+06            7.604539e+05        2382
9        Mumbai           3.905862e+06            5.193110e+05        2521
10  Grand Total           3.259310e+07            4.785877e+06       18683

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Row Labels              11 non-null     object
 1   Sum of Monthly_Income   11 non-null     float64
 2   Sum of Purchase_Amount  11 non-null     float64
 3   Sum of Age              11 non-null     int64
dtypes: float64(2), int64(1), object(1)
memory usage: 484.0+ bytes

In [5]:
df.describe()

       Sum of Monthly_Income  Sum of Purchase_Amount    Sum of Age
count           1.100000e+01            1.100000e+01     11.000000
mean            8.889028e+06            1.305239e+06   5095.363636
std             9.266462e+06            1.361893e+06   5318.362159
min             3.301398e+06            5.193110e+05   1560.000000
25%             3.962049e+06            5.405359e+05   2394.000000
50%             4.118840e+06            6.154198e+05   2521.000000
75%             1.045540e+07            1.530766e+06   6007.000000
max             3.259310e+07            4.785877e+06  18683.000000

In [8]:
df.isnull()

    Row Labels  Sum of Monthly_Income  Sum of Purchase_Amount  Sum of Age
0        False                  False                   False       False
1        False                  False                   False       False
2        False                  False                   False       False
3        False                  False                   False       False
4        False                  False                   False       False
5        False                  False                   False       False
6        False                  False                   False       False
7        False                  False                   False       False
8        False                  False                   False       False
9        False                  False                   False       False
10       False                  False                   False       False